// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVariable(ctx context.Context, arg CreateVariableParams) (Variable, error)
	DeleteEnvironment(ctx context.Context, id pgtype.UUID) error
	DeleteOrganization(ctx context.Context, id pgtype.UUID) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteVariable(ctx context.Context, arg DeleteVariableParams) error
	GetEnvironment(ctx context.Context, id pgtype.UUID) (Environment, error)
	GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListEnvironments(ctx context.Context, projectID pgtype.UUID) ([]Environment, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListProjects(ctx context.Context, organizationID pgtype.UUID) ([]Project, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListVariables(ctx context.Context, environmentID pgtype.UUID) ([]Variable, error)
	UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVariable(ctx context.Context, arg UpdateVariableParams) (Variable, error)
}

var _ Querier = (*Queries)(nil)
