// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVariable(ctx context.Context, arg CreateVariableParams) (Variable, error)
	DeleteEnvironment(ctx context.Context, id pgtype.UUID) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteVariable(ctx context.Context, arg DeleteVariableParams) error
	GetEnvironment(ctx context.Context, id pgtype.UUID) (Environment, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByResetToken(ctx context.Context, passwordResetToken pgtype.Text) (User, error)
	ListActiveRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) ([]RefreshToken, error)
	ListEnvironments(ctx context.Context, projectID pgtype.UUID) ([]Environment, error)
	ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error)
	ListProjects(ctx context.Context, userID pgtype.UUID) ([]ListProjectsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListVariables(ctx context.Context, environmentID pgtype.UUID) ([]Variable, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	RevokeRefreshToken(ctx context.Context, token string) error
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error
	UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVariable(ctx context.Context, arg UpdateVariableParams) (Variable, error)
}

var _ Querier = (*Queries)(nil)
