# These are supported funding model platforms

github: [nyambogahezron]
patreon: nyambogahezron
open_collective: nyambogahezron
ko_fi: nyambogahezron
community_bridge: nyambogahezron
liberapay: nyambogahezron
issuehunt: nyambogahezron
polar: nyambogahezron
buy_me_a_coffee: nyambogahezron
custom: nyambogahezron
